import {createQrMatrix,createQrSvgPath} from './lib/qr-code.mjs';
import {readStoredIotReadings,saveStoredIotReading} from './lib/iot-local-store.mjs';
import {labelForEvent,labelForProof} from './lib/display-labels.mjs';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],name=location.pathname.split('/').pop();
const labels={createBatch:'Tạo lô',recordPlanting:'Ghi gieo trồng',recordCare:'Ghi chăm sóc',recordHarvest:'Ghi thu hoạch',createShipment:'Tạo chuyến vận chuyển',reportDamage:'Báo hỏng',startTransport:'Bắt đầu vận chuyển',completeTransport:'Hoàn tất vận chuyển',receiveRetail:'Nhận lô',rejectRetail:'Từ chối lô',markForSale:'Đưa lên kệ'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,options){const r=await fetch('/api'+url,options);const data=await r.json();if(!r.ok)throw Error(data.message||'Không thực hiện được thao tác.');return data;}
function dialog(title,content){const d=document.createElement('dialog');d.className='bg-white p-6 rounded-xl border border-slate-200 shadow-xl w-full max-w-xl';d.innerHTML=`<div class="flex justify-between items-center mb-5"><h2 class="text-xl font-bold text-slate-800">${esc(title)}</h2><button type="button" class="btn-outline px-3 py-2" aria-label="Đóng">Đóng</button></div>${content}`;document.body.append(d);d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d;}
const message=(text,title='Thông báo')=>dialog(title,`<p class="text-sm text-slate-600" role="status">${esc(text)}</p>`);
function qrSvg(value){const m=createQrMatrix(value),s=m.length+8;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${s} ${s}" width="224" height="224" role="img" aria-label="Mã QR truy xuất"><rect width="${s}" height="${s}" fill="white"/><path d="${createQrSvgPath(m)}" fill="#17211d" transform="translate(4 4)"/></svg>`;}
function bind(el,fn){if(!el)return;el.removeAttribute('onclick');el.addEventListener('click',e=>{e.preventDefault();Promise.resolve(fn(e)).catch(e=>message(e.message,'Không thể hoàn tất'));});}
const buttonText=(t,p=document)=>$$('button,a',p).find(b=>b.textContent.trim()===t);
function setLabel(el,text){if(!el)return;for(const n of [...el.childNodes])if(n.nodeType===Node.TEXT_NODE)n.remove();el.append(document.createTextNode(' '+text));}
async function getBatch(){const id=new URLSearchParams(location.search).get('batchId');return id?api('/trace/'+encodeURIComponent(id)):(await api('/batches'))[0];}
function showQr(b){const url=location.origin+'/wireframes/public/trace-detail.html?batchId='+encodeURIComponent(b.batchId);const d=dialog('Mã QR truy xuất',`<div class="flex justify-center">${qrSvg(url)}</div><p class="text-sm font-semibold mt-4">${esc(b.productName)} · ${esc(b.batchCode)}</p><div class="flex gap-3 mt-5"><a href="${esc(url)}" class="btn-primary px-4 py-2">Mở truy xuất</a><button class="btn-outline px-4 py-2" data-download>Tải SVG</button></div>`);bind($('[data-download]',d),()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([qrSvg(url)],{type:'image/svg+xml'}));a.href=u;a.download=b.batchCode+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});}
async function traceSearch(value){let code=value.trim();try{const u=new URL(code);code=u.searchParams.get('batchId')||decodeURIComponent(u.pathname.split('/').pop());}catch{}if(!code)throw Error('Vui lòng nhập mã truy xuất.');const b=await api('/trace/'+encodeURIComponent(code));location.href='/wireframes/public/trace-detail.html?batchId='+encodeURIComponent(b.batchId);}
// Add event handlers only. Original HTML and all style rules remain untouched.
if(name==='trace-search.html'){
 const input=$('.search-container input');bind($('.search-container a'),()=>traceSearch(input.value));input?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();traceSearch(input.value).catch(e=>message(e.message,'Không tìm thấy mã'));}});
 for(const a of $$('a').filter(a=>/^AT\d+$/.test(a.textContent.trim())))bind(a,()=>traceSearch(a.textContent));
}
if(name==='home.html')for(const input of $$('input').filter(i=>/mã|truy xuất/i.test(i.placeholder))){input.addEventListener('keydown',e=>{if(e.key==='Enter')traceSearch(input.value).catch(e=>message(e.message));});const area=input.parentElement;bind($('button,a',area),()=>traceSearch(input.value));}
if(name==='login.html'){
 const form=$('form'),password=$('input[type=password]',form),toggle=password?.parentElement.querySelector('button');
 bind(toggle,()=>{password.type=password.type==='password'?'text':'password';toggle.setAttribute('aria-label',password.type==='password'?'Hiện mật khẩu':'Ẩn mật khẩu');});
 form?.removeAttribute('onsubmit');form?.addEventListener('submit',async e=>{e.preventDefault();const login=$('input[type=text]',form);if(!login.value.trim()||!password.value)return message('Vui lòng nhập tài khoản và mật khẩu.');try{const session=await api('/session');sessionStorage.setItem('agritrace:session',JSON.stringify(session));if($('input[type=checkbox]',form)?.checked)localStorage.setItem('agritrace:remembered-user',login.value);location.href='../admin/dashboard.html';}catch(e){message(e.message);}});
 const saved=localStorage.getItem('agritrace:remembered-user');if(saved)$('input[type=text]',form).value=saved;
}
function inputField(label,type,value,key){return `<label class="block text-sm font-medium text-slate-700 mb-4">${esc(label)}<input name="${key}" type="${type}" value="${esc(value)}" required class="w-full px-3 py-2.5 border border-slate-200 rounded-lg mt-1 focus:outline-none focus:ring-2 focus:ring-primary-200"></label>`;}
async function sensorForm(){const batches=await api('/batches'),last=readStoredIotReadings()[0];const d=dialog('Gửi dữ liệu IoT giả lập',`<form>${inputField('Thiết bị','text',last?.deviceId||'device-cu-chi-01','deviceId')}<label class="block text-sm font-medium mb-4">Lô nông sản<select name="batchId" class="w-full px-3 py-2.5 border border-slate-200 rounded-lg mt-1">${batches.map(b=>`<option value="${esc(b.batchId)}">${esc(b.batchCode+' · '+b.productName)}</option>`).join('')}</select></label><div class="grid grid-cols-2 gap-4">${inputField('Nhiệt độ (°C)','number',last?.temperature??27.5,'temperature')}${inputField('Độ ẩm (%)','number',last?.humidity??68,'humidity')}</div>${inputField('Thời điểm UTC','text',new Date().toISOString(),'timestampUtc')}<div class="flex gap-3"><button class="btn-primary px-4 py-2" type="submit">Gửi dữ liệu</button><button type="button" data-retry class="btn-outline px-4 py-2">Gửi lại lần gần nhất</button></div><p data-result role="status" class="text-sm text-slate-600 mt-4"></p></form>`);$$('input[type=number]',d).forEach(i=>i.step='any');
 async function send(payload){const submit=$('button[type=submit]',d),result=$('[data-result]',d);submit.disabled=true;try{const r=await api('/iot/readings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(r.status!=='accepted')throw Error(r.error?.message||'Dữ liệu bị từ chối.');saveStoredIotReading({...payload,readingId:r.readingId,acceptedAt:new Date().toISOString(),status:'accepted'});result.textContent='Đã tiếp nhận · '+r.readingId;updateReadings();}catch(e){result.textContent=e.message;}finally{submit.disabled=false;}}
 $('form',d).onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));send({...v,temperature:Number(v.temperature),humidity:Number(v.humidity)});};bind($('[data-retry]',d),()=>{const r=readStoredIotReadings()[0];if(r)return send(r);$('[data-result]',d).textContent='Chưa có lần gửi gần nhất.';});
}
function updateReadings(){const readings=readStoredIotReadings();if(!readings.length)return;
 const heading=$$('h3').find(h=>/Thông số Live/.test(h.textContent));if(heading){const parent=heading.closest('.bg-slate-800')||heading.parentElement.parentElement;const blocks=$$('p.text-2xl',parent);if(blocks[0])blocks[0].firstChild.textContent=String(readings[0].temperature);if(blocks[1])blocks[1].firstChild.textContent=String(readings[0].humidity);}
 const history=$$('h3').find(h=>/Lịch sử bản ghi/.test(h.textContent));const tbody=history?.closest('.card')?.querySelector('tbody');if(tbody){const template=tbody.rows[0]?.cloneNode(true);if(template){tbody.replaceChildren(...readings.slice(0,4).map(r=>{const row=template.cloneNode(true);[r.readingId,r.batchId,new Date(r.timestampUtc).toLocaleString('vi-VN'),`${r.temperature}°C / ${r.humidity}%`].forEach((t,i)=>{if(row.cells[i])row.cells[i].textContent=t;});return row;}));}}
}
if(name==='iot.html'){
 const first=$('main .btn-primary');if(first){const b=first.cloneNode(true);b.removeAttribute('onclick');b.textContent='Gửi dữ liệu giả lập';first.after(b);bind(b,sensorForm);}updateReadings();
 const search=$('input[placeholder*="thiết bị"]');search?.addEventListener('input',()=>{for(const b of $$('button').filter(b=>b.textContent.includes('Chi tiết →'))){const card=b.closest('[class*="group"]')||b.parentElement.parentElement;card.hidden=!card.textContent.toLowerCase().includes(search.value.toLowerCase());}});
}
function showReadings(){const list=readStoredIotReadings();dialog('Dữ liệu IoT đã gửi',list.length?`<div class="space-y-3">${list.map(r=>`<div class="border border-slate-200 rounded-lg p-3"><strong>${esc(r.batchId)}</strong><p class="text-sm">${esc(r.temperature)}°C · ${esc(r.humidity)}% · ${esc(r.timestampUtc)}</p></div>`).join('')}</div>`:'<p class="text-sm text-slate-500">Chưa có dữ liệu gửi trong trình duyệt này.</p>');}
if(name==='dashboard.html'){const h=$$('h3').find(h=>/Thao tác nhanh/.test(h.textContent));if(h){const a=document.createElement('button');a.className='btn-outline px-4 py-2 text-sm';a.textContent='Dữ liệu IoT đã gửi';h.parentElement.append(a);bind(a,showReadings);}}
if(name==='dashboard.html'){
 try{const [dashboard,batches]=await Promise.all([api('/dashboard'),api('/batches')]);
 const values=['—',String(batches.length),String(batches.filter(b=>b.currentState==='IN_TRANSPORT').length),String(batches.filter(b=>b.currentState==='FOR_SALE').length),'—'];
 $$('.kpi-card').forEach((card,i)=>{const count=$('.counter-value',card);if(count)count.textContent=values[i];const detail=$('p:last-child',count?.parentElement||card);if(detail&&detail!==count)setLabel(detail,values[i]==='—'?'Chưa có dữ liệu':'Theo dữ liệu hiện có');});
 for(const [text,command] of [['Ghi nhận chăm sóc','recordCare'],['Tạo lô thu hoạch','recordHarvest']])bind(buttonText(text),async()=>{const b=dashboard.featuredBatch;if(!b.allowedCommands.includes(command))throw Error('Lô hiện tại không cho phép thao tác này.');const r=await api(`/batches/${encodeURIComponent(b.batchId)}/commands/${command}`,{method:'POST'});message(r.message,'Kết quả thao tác');});
 }catch(e){message(e.message);}
}
if(name==='lots-list.html'){
 try{const batches=await api('/batches'),body=$('tbody'),template=body.rows[0].cloneNode(true);body.replaceChildren(...batches.map(b=>{const r=template.cloneNode(true);r.dataset.batchId=b.batchId;r.dataset.state=b.currentState;r.dataset.proof=b.proofStatus;r.cells[0].textContent=b.batchCode;$('span',r.cells[1]).textContent=b.productName;r.cells[2].textContent='—';r.cells[3].textContent='—';$('span',r.cells[4]).textContent=b.currentState;r.cells[5].textContent='—';r.cells[6].textContent=labelForProof(b.proofStatus);$('a',r.cells[7]).href='lot-detail.html?batchId='+encodeURIComponent(b.batchId);return r;}));const h=$$('h3').find(h=>h.textContent.includes('Danh sách lô hàng'));const counter=h?.parentElement.querySelector('p');if(counter)counter.textContent=`${batches.length} lô từ nguồn dữ liệu KhoaLuan`;
 let state='';const search=$('input[placeholder*="mã lô, sản phẩm"]'),[proof,product]=$$('main select');if(product)product.replaceChildren(new Option('Tất cả sản phẩm',''),...[...new Set(batches.map(b=>b.productName))].map(p=>new Option(p,p)));function filter(){for(const row of body.rows){const b=batches.find(b=>b.batchId===row.dataset.batchId);const proofValue={VERIFIED:'verified',PROOF_PENDING:'pending',INTEGRITY_WARNING:'warning'}[proof?.value];row.hidden=!!(state&&row.dataset.state!==state)||!!(product?.value&&b.productName!==product.value)||!!(proofValue&&b.proofStatus!==proofValue)||!row.textContent.toLowerCase().includes((search?.value||'').toLowerCase());row.style.display=row.hidden?'none':'';}}search?.addEventListener('input',filter);proof?.addEventListener('change',filter);product?.addEventListener('change',filter);for(const button of $$('.filter-pill'))bind(button,()=>{state=button.textContent.trim()==='Tất cả'?'':button.textContent.trim();$$('.filter-pill').forEach(b=>b.classList.toggle('active',b===button));filter();});
 }catch(e){message(e.message);}
}
async function showCommands(batch,anchor){const area=anchor||document.createElement('div');if(!anchor){area.className='flex flex-wrap gap-3 mt-4';$('main h1')?.parentElement.append(area);}for(const c of batch.allowedCommands){const b=document.createElement('button');b.className='btn-primary px-4 py-2 text-sm';b.textContent=labels[c]||c;b.dataset.command=c;area.append(b);bind(b,async()=>{b.disabled=true;try{const r=await api(`/batches/${encodeURIComponent(batch.batchId)}/commands/${c}`,{method:'POST'});message(r.message,'Kết quả thao tác');}finally{b.disabled=false;}});}}
function replaceText(root,oldValue,newValue){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(['SCRIPT','STYLE'].includes(n.parentElement?.tagName))continue;n.textContent=n.textContent.split(oldValue).join(newValue);}}
if(name==='lot-detail.html'){
 try{const batch=await getBatch();replaceText(document.body,'LOT-2026-0001',batch.batchCode);replaceText(document.body,'Rau cải xanh',batch.productName);
 replaceText($('main'),'Nông trại An Phú',batch.farmOrg.name);replaceText($('main'),'FreshMart Quận 7',batch.retailerOrg?.name||'Chưa có đơn vị bán lẻ');
 for(const p of $$('.qty-card p.text-2xl'))setLabel(p,'—');
 for(const span of $$('main span')){if(span.textContent.trim()==='FOR_SALE')span.textContent=batch.currentState;if(span.textContent.trim()==='Thu hoạch: 15/03/2026')span.textContent='Thu hoạch: chưa có dữ liệu';}
 const first=$('main button[onclick*="damageModal"]'),area=first?.parentElement;if(area){area.replaceChildren();await showCommands(batch,area);}else await showCommands(batch);
 const timeline=$('#tab-timeline .timeline-container');if(timeline){const template=$('.timeline-event',timeline)?.cloneNode(true),line=$('.timeline-vline',timeline);if(template){timeline.replaceChildren(...(line?[line]:[]),...batch.timeline.map(e=>{const row=template.cloneNode(true);$('h4',row).textContent=labelForEvent(e.eventType);$('p',row).textContent=e.summary;const time=$('.whitespace-nowrap',row);if(time)time.textContent=new Date(e.eventTime).toLocaleString('vi-VN');return row;}));}}
 for(const [index,row] of $$('.timeline-event').entries())setLabel($('span.inline-flex',row),labelForProof(batch.timeline[index].proofStatus));
 const proof=$('#tab-blockchain .font-mono');if(proof){const template=$('p',proof).cloneNode(true);proof.replaceChildren(...Object.entries(batch.blockchainProof).map(([k,v])=>{const p=template.cloneNode(true);$('span',p).textContent=k+':';setLabel(p,String(v));return p;}));}
 for(const a of $$('a[href*="public/trace-detail.html"]'))a.href='../public/trace-detail.html?batchId='+encodeURIComponent(batch.batchId);
 const qrHeading=$$('h3').find(h=>/Mã QR Truy xuất/.test(h.textContent));const qrBox=qrHeading?.nextElementSibling;if(qrBox){const old=$('svg',qrBox);if(old){const wrapper=document.createElement('div');wrapper.innerHTML=qrSvg(location.origin+'/wireframes/public/trace-detail.html?batchId='+encodeURIComponent(batch.batchId));const svg=wrapper.firstElementChild;svg.setAttribute('class',old.getAttribute('class'));svg.removeAttribute('width');svg.removeAttribute('height');old.replaceWith(svg);}}
 for(const b of $$('button').filter(b=>/QR|Tải mã|In tem/.test(b.textContent)))bind(b,()=>showQr(batch));
 }catch(e){message(e.message);}
}
if(name==='trace-detail.html'){
 const id=new URLSearchParams(location.search).get('batchId');let batch;
 try{batch=await getBatch();$('main h1').textContent=batch.productName;replaceText($('main'),'AT000123456',batch.batchCode);replaceText($('main'),'LOT-2026-0001',batch.batchCode);replaceText($('main'),'Nông trại An Phú',batch.farmOrg.name);for(const label of $$('main p')){const t=label.textContent.trim();if(t==='Nguồn gốc')label.nextElementSibling.textContent=batch.farmOrg.name;if(t==='Ngày thu hoạch')label.nextElementSibling.textContent=batch.timeline.find(e=>e.eventType==='HARVEST_RECORDED')?.eventTime||'Chưa có dữ liệu';if(t==='Trạng thái')label.nextElementSibling.textContent=batch.currentState;}}catch(e){message(e.message);}
 const tabs=$$('button').filter(b=>['Tổng quan & Hành trình','Dữ liệu IoT','Chứng nhận'].includes(b.textContent.trim()));
 bind(tabs[1],showReadings);bind(tabs[2],()=>{const target=$$('h3,h4').find(h=>/Chứng nhận/.test(h.textContent));if(target)target.scrollIntoView({behavior:'smooth',block:'center'});else message('Nguồn dữ liệu KhoaLuan chưa cung cấp tài liệu chứng nhận.');});
 bind(tabs[0],()=>$$('h3').find(h=>/Hành trình sản phẩm/.test(h.textContent))?.scrollIntoView({behavior:'smooth'}));
 for(const b of $$('button').filter(b=>/Quét mã khác/.test(b.textContent)))bind(b,()=>{location.href='trace-search.html';});
 for(const b of $$('button').filter(b=>/Chia sẻ/.test(b.textContent)))bind(b,async()=>{await navigator.clipboard.writeText(location.href);message('Đã sao chép đường dẫn truy xuất.');});
 if(batch){const h=$$('h3').find(h=>/Hành trình sản phẩm/.test(h.textContent));const list=h?.parentElement.querySelector('.relative.pl-2');if(list){const template=$('.timeline-item',list);if(template){const copy=template.cloneNode(true),line=$('.timeline-line',list);list.replaceChildren(...(line?[line]:[]),...batch.timeline.map(e=>{const item=copy.cloneNode(true);item.classList.add('visible');const heading=$('h4,h3',item);if(heading){heading.textContent=labelForEvent(e.eventType);heading.nextElementSibling.textContent=new Date(e.eventTime).toLocaleString('vi-VN');}setLabel($('p',item),e.actor.organizationName);setLabel($('span.inline-flex',item),labelForProof(e.proofStatus));const tx=$('a[title="Transaction Hash"]',item);if(tx){tx.textContent=e.eventId;tx.title=e.summary;bind(tx,()=>message(e.summary,'Chi tiết sự kiện'));}return item;}));}}}
}
// Other original table searches retain their own rows and their exact presentation.
if(!['lots-list.html','iot.html','trace-search.html'].includes(name))for(const input of $$('input').filter(i=>/tìm kiếm/i.test(i.placeholder))){input.addEventListener('input',()=>{for(const r of $$('tbody tr'))r.hidden=!r.textContent.toLowerCase().includes(input.value.toLowerCase());});}
