const {chromium}=require('C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const root='http://localhost:3100';
const out=path.join(__dirname,'verification');fs.mkdirSync(out,{recursive:true});const original=await page.request.get(root+'/wireframes/public/home.html?reference'),functional=await page.request.get(root+'/wireframes/public/home.html');assert.equal((await functional.text()).replace('<script type="module" src="/functionality/client.mjs"></script>',''),await original.text());
for(const route of ['/wireframes/public/home.html','/wireframes/public/login.html','/wireframes/admin/dashboard.html','/wireframes/admin/iot.html']){await page.goto(root+route);await page.waitForLoadState('networkidle');if(route.endsWith('home.html'))await page.screenshot({path:path.join(out,'home.png'),fullPage:true});}
await page.goto(root+'/wireframes/public/trace-search.html');await page.locator('.search-container input').fill('AT000123456');await page.locator('.search-container a').click();await page.waitForURL('**/trace-detail.html?batchId=batch-rau-001');await page.waitForFunction(()=>document.querySelector('main h1')?.textContent==='Rau cải ngọt');
await page.goto(root+'/wireframes/public/trace-search.html');await page.locator('.search-container input').fill('INVALID');await page.locator('.search-container a').click();await page.getByRole('dialog').waitFor();assert((await page.getByRole('dialog').textContent()).includes('Không tìm thấy'));
await page.goto(root+'/wireframes/admin/lots-list.html');await page.waitForFunction(()=>document.querySelectorAll('tbody tr').length===2);await page.locator('input[placeholder*="mã lô, sản phẩm"]').fill('Xoài');await page.locator('tbody tr:visible a').click();await page.waitForURL('**/lot-detail.html?batchId=batch-xoai-002');await page.locator('[data-command="completeTransport"]').click();await page.getByRole('dialog').waitFor();assert((await page.getByRole('dialog').textContent()).includes('Đã tiếp nhận thao tác'));await page.getByRole('button',{name:'Đóng',exact:true}).click();
const denied=await page.request.post(root+'/api/batches/batch-rau-001/commands/completeTransport');assert.equal(denied.status(),403);
await page.getByRole('button',{name:'Tải QR',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.locator('dialog svg[aria-label="Mã QR truy xuất"]').count(),1);const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Tải SVG',exact:true}).click();assert.equal((await downloaded).suggestedFilename(),'XOA-NBE-2026-002.svg');await page.getByRole('link',{name:'Mở truy xuất',exact:true}).click();await page.waitForFunction(()=>document.querySelector('main h1')?.textContent==='Xoài cát');assert.equal(await page.locator('.timeline-item').count(),2);assert((await page.locator('.timeline-item').first().textContent()).includes('2026'));await page.locator('.timeline-item').first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'trace-functional.png')});
await page.goto(root+'/wireframes/admin/iot.html');await page.getByRole('button',{name:'Gửi dữ liệu giả lập',exact:true}).click();await page.locator('dialog input[name="temperature"]').fill('26.5');await page.getByRole('button',{name:'Gửi dữ liệu',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-result]')?.textContent.includes('Đã tiếp nhận'));await page.getByRole('button',{name:'Gửi lại lần gần nhất'}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('agri-traceability:iot-readings')).length===2);await page.goto(root+'/wireframes/admin/dashboard.html');await page.getByRole('button',{name:'Dữ liệu IoT đã gửi'}).click();assert((await page.getByRole('dialog').textContent()).includes('26.5'));
await page.goto(root+'/wireframes/public/login.html');await page.locator('form input[type=text]').fill('demo@example.com');await page.locator('form input[type=password]').fill('demo');await page.locator('form input[type=password]').locator('..').getByRole('button').click();assert.equal(await page.locator('form input[type=password]').count(),0);await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await page.waitForURL('**/admin/dashboard.html');
assert.deepEqual(errors,[]);const report={passed:true,originalHomeMarkupUnchanged:true,flows:['QR mẫu','QR sai','lọc lô và chi tiết','gửi thao tác','chặn thao tác ngoài allowedCommands','IoT gửi/gửi lại/lưu/dashboard','đăng nhập mô phỏng và hiện mật khẩu'],browserErrors:errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
